# Syntax highlighting
highlighter:         pygments

# Permalinks
permalink:           pretty

# Setup
title:               Jekyll Example

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed
